---------------ȸ�����̺�----------------------
CREATE TABLE TBL_MEMBER(
	USERIDX NUMBER(4),
	USERID VARCHAR2(100) UNIQUE,
	USERPW VARCHAR2(150),
	USERNAME VARCHAR2(100),
	USERPHONE VARCHAR2(100),
	USERADDR VARCHAR2(250),
	USERPOINT NUMBER(7) DEFAULT 0,
	CONSTRAINT TBL_MEMBER_PK PRIMARY KEY (USERIDX)
);

CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1;
--* �⺻ ���� ���� �߰� *
INSERT INTO TBL_MEMBER VALUES (SEQ_USER.NEXTVAL,'apple','efgh56789:','����','01022334455','������',0);
INSERT INTO TBL_MEMBER VALUES (SEQ_USER.NEXTVAL,'banana','efgh56789:','���ϳ�','01033445566','������',0);

----------------��ǰ���̺�----------------------
-- *������ �������� �ƴϱ� ������ ��ǰ �߰��� �⺻ ���� 100���� ������*
CREATE TABLE TBL_PRODUCT (
	PRODIDX NUMBER(4),
	PRODDATE DATE DEFAULT SYSDATE,
	PRODNAME VARCHAR2(150) UNIQUE,
	PRODDES VARCHAR2(250),
	PRODPRICE NUMBER(10),
	PRODLIKE NUMBER(10) DEFAULT 0,
	PRODAMOUNT NUMBER(10) DEFAULT 100,
	CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY (PRODIDX)
);

CREATE SEQUENCE SEQ_PROD
START WITH 1
INCREMENT BY 1;

--*�⺻ ���� ��ǰ �߰�*
INSERT INTO TBL_PRODUCT (PRODIDX,PRODNAME,PRODDES,PRODPRICE)
VALUES (SEQ_PROD.NEXTVAL,'지우개','잘지워져요!',500);
INSERT INTO TBL_PRODUCT (PRODIDX,PRODNAME,PRODDES,PRODPRICE)
VALUES (SEQ_PROD.NEXTVAL,'����','�� ������^^',1500);
INSERT INTO TBL_PRODUCT (PRODIDX,PRODNAME,PRODDES,PRODPRICE,PRODAMOUNT)
VALUES (SEQ_PROD.NEXTVAL,'��å','�� �����@',2000,0);

----------------�ֹ����̺�----------------------
CREATE TABLE TBL_ORDERLIST(
	ORDERIDX NUMBER(4),
	USERID VARCHAR2(100),
	PRODIDX NUMBER(4),
	ORDERSTATES VARCHAR2(100),
	CONSTRAINT TBL_ORDERLIST_PK PRIMARY KEY (ORDERIDX),
	CONSTRAINT TBL_ORDERLIST_FK1 FOREIGN KEY (USERID) REFERENCES TBL_MEMBER (USERID),
	CONSTRAINT TBL_ORDERLIST_FK2 FOREIGN KEY (PRODIDX) REFERENCES TBL_PRODUCT (PRODIDX)
);

CREATE SEQUENCE SEQ_ORDER
START WITH 1
INCREMENT BY 1;

----------------��ٱ������̺�----------------------
CREATE TABLE TBL_BASKET(
	BASKETIDX NUMBER(4),
	USERID VARCHAR2(100),
	PRODIDX NUMBER(4),
	CONSTRAINT TBL_BASKET_PK PRIMARY KEY (BASKETIDX),
	CONSTRAINT TBL_BASKET_FK1 FOREIGN KEY (USERID) REFERENCES TBL_MEMBER (USERID),
	CONSTRAINT TBL_BASKET_FK2 FOREIGN KEY (PRODIDX) REFERENCES TBL_PRODUCT (PRODIDX)
);

CREATE SEQUENCE SEQ_BASKET
START WITH 1
INCREMENT BY 1;

----------------�Խ������̺�----------------------
CREATE TABLE TBL_BOARD(
	BOARDIDX NUMBER(4),
	USERID VARCHAR2(100),
	BOARDTITLE VARCHAR2(200),
	BOARDCONTENTS VARCHAR2(1000),
	BOARDDATE DATE DEFAULT SYSDATE,
	CONSTRAINT TBL_BOARD_PK PRIMARY KEY(BOARDIDX),
	CONSTRAINT TBL_BOARD_KF FOREIGN KEY(USERID) REFERENCES TBL_MEMBER (USERID)
);

CREATE SEQUENCE SEQ_BOARD
START WITH 1
INCREMENT BY 1;

--*�⺻ ���� ���� �߰�*
INSERT INTO TBL_BOARD(BOARDIDX,USERID,BOARDTITLE,BOARDCONTENTS)
VALUES (SEQ_BOARD.NEXTVAL,'apple','���찳 ���� ���� �Դϴ�!','���찳 ���� �� ����������???');
INSERT INTO TBL_BOARD(BOARDIDX,USERID,BOARDTITLE,BOARDCONTENTS)
VALUES (SEQ_BOARD.NEXTVAL,'banana','���� ���� �����Դϴ�~~','���� ���� �� ��������???');

----------------------DDL--------------------------------
SELECT * FROM TBL_BOARD WHERE BOARDIDX = 1;
DROP TABLE TBL_MEMBER;
DROP SEQUENCE SEQ_USER;

DROP TABLE TBL_PRODUCT;
DROP SEQUENCE SEQ_PROD;

DROP TABLE TBL_ORDERLIST;
DROP SEQUENCE SEQ_ORDER;

DROP TABLE TBL_BASKET;
DROP SEQUENCE SEQ_BASKET;

DROP TABLE TBL_BOARD;
DROP SEQUENCE SEQ_BOARD;


SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_ORDERLIST;
SELECT * FROM TBL_BASKET;
SELECT * FROM TBL_BOARD;



